name: Maven Test and Report

on:
  push:
    branches: [ pos-test-ci ]
  pull_request:
    branches: [ pos-test-ci ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: â¬‡ï¸ Checkout repository
      uses: actions/checkout@v4

    - name: â˜• Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: ğŸ§° Set up Allure CLI
      uses: actions/setup-node@v3

    - name: ğŸ“¦ Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: ğŸ§ª Build and test with Maven
      run: mvn clean test site allure:report

    - name: ğŸ“¦ Upload Surefire HTML Report
      uses: actions/upload-artifact@v3.1.3
      with:
        name: surefire-report
        path: target/site/surefire-report.html

    - name: ğŸ“¦ Upload Allure HTML Report
      uses: actions/upload-artifact@v3.1.3
      with:
        name: allure-report
        path: target/site/allure-maven-plugin/index.html
